# ComputerCraft: Tweaked
[cctweaked]
base = "lua51"
name = "cctweaked"

[cctweaked.structs.colors."*"]

[cctweaked.structs.colours."*"]

[cctweaked.structs.commands."*"]

[cctweaked.structs.disk."*"]

[cctweaked.structs.fs."*"]

[cctweaked.structs.gps."*"]

[cctweaked.structs.help."*"]

[cctweaked.structs.http."*"]

[cctweaked.structs.keys."*"]

[cctweaked.structs.multishell."*"]

[cctweaked.structs.paintutils."*"]

[cctweaked.structs.parallel."*"]

[cctweaked.structs.peripheral."*"]

[cctweaked.structs.pocket."*"]

[cctweaked.structs.rednet."*"]

[cctweaked.structs.redstone."*"]

[cctweaked.structs.settings."*"]

[cctweaked.structs.shell."*"]

[cctweaked.structs.term."*"]

[cctweaked.structs.textutils."*"]

[cctweaked.structs.turtle."*"]

[cctweaked.structs.vector."*"]

[cctweaked.structs.window."*"]