# ComputerCraft: Tweaked
[cctweaked]
base = "lua51"
name = "cctweaked"

[cctweaked.colors]

[cctweaked.colours]

[cctweaked.commands]

[cctweaked.disk]

[cctweaked.fs]

[cctweaked.gps]

[cctweaked.help]

[cctweaked.http]

[cctweaked.keys]

[cctweaked.multishell]

[cctweaked.paintutils]

[cctweaked.parallel]

[cctweaked.peripheral]

[cctweaked.pocket]

[cctweaked.rednet]

[cctweaked.redstone]

[cctweaked.settings]

[cctweaked.shell]

[cctweaked.term]

[cctweaked.textutils]

[cctweaked.turtle]

[cctweaked.vector]

[cctweaked.window]